name: Trigger on New Release

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # 매일 00:00에 실행하도록 예약

jobs:
  check-new-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest release
        id: get_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/anddea/revanced-patches/releases/latest | jq -r '.tag_name')
          echo "::set-output name=tag::$latest_release"

      - name: Compare with previous release
        id: compare_release
        run: |
          previous_release=$(git describe --abbrev=0 --tags)
          echo "::set-output name=previous_tag::$previous_release"

      - name: Logging if new release
        if: ${{ steps.compare_release.outputs.tag != steps.get_release.outputs.tag }}
        run: |
          echo "New release detected: ${{ steps.get_release.outputs.tag }}"
          # 여기에 작업을 추가합니다.

      - name: Trigger workflow if new release
        if: ${{ steps.compare_release.outputs.tag != steps.get_release.outputs.tag }}
        uses: actions/build-apk@main
