name: Check for Latest Release

on:
  workflow_dispatch:  
    inputs:
      GITHUB_UPLOAD:
        description: "Upload to GitHub"
        required: false
        type: boolean
        default: true
      TELEGRAM_NO_ROOT_UPLOAD:
        description: "Upload Non Rooted APKs to Telegram"
        required: false
        type: boolean
        default: false
      TELEGRAM_ROOT_UPLOAD:
        description: "Upload Magisk Module from nikhilbadyal/revanced-magisk-module to Telegram"
        required: false
        type: boolean
        default: false
      APPRISE_NOTIFY:
        description: "Use Apprise to Notify"
        required: false
        type: boolean
        default: false
      VIRUSTOTAL_SCAN:
        description: "Scan apks with VirusTotal"
        required: false
        type: boolean
        default: false
      CLEANUP:
        description: "Clear GitHub(Useful if Telegram upload is enabled)"
        required: false
        type: boolean
        default: false
      COMMIT_CHANGELOG:
        description: "Update Changelog"
        type: boolean
        required: false
        default: false
      DEBUG_ENABLED:
        type: boolean
        description: 'Run the build with tmate debugging enabled.'
        required: false
        default: false
  schedule:
    - cron: '0 * * * *'  # 정각마다 실행
    
concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
    
jobs:        
    check-release:
      runs-on: ubuntu-latest

      steps:
      - name: checkout repo content
        uses: actions/checkout@main
        
      - name: Get latest release
        id: latest_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/anddea/revanced-patches/releases/latest | jq -r '.created_at')
          echo "::set-output name=latest_release::$latest_release"
        
      - name: Calculate time difference
        id: time_difference
        run: |
          latest_release=${{ steps.latest_release.outputs.latest_release }}
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          latest_release_time=$(date -d "$latest_release" -u +"%s")
          current_time=$(date -d "$current_time" -u +"%s")
          difference=$((current_time - latest_release_time))
          echo "::set-output name=difference::$difference"
        
      - name: Check time difference
        id: check_time
        run: |
          difference=${{ steps.time_difference.outputs.difference }}
          threshold=$((60 * 60)) # 1 시간 in seconds
          if [ $difference -ge $threshold ]; then
            echo "Time difference is greater than or equal to 30 minutes."
            exit 0
          else
            echo "Time difference is less than 30 minutes."
            exit 1
          fi
        
      - name: Perform action on release
        if: ${{ success() }}
        run: |
          echo "Performing action on release with time difference greater than or equal to 30 minutes."     
      
    build-apk:
      needs: check-release
      uses: ./.github/workflows/build-artifact.yml
      with:
        COMMIT_CHANGELOG: ${{ inputs.COMMIT_CHANGELOG }}
        DEBUG_ENABLED: ${{ inputs.DEBUG_ENABLED }}
      secrets:
        ENVS: ${{ secrets.ENVS }}
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}


    upload-to-github:
      name: GitHub Upload
      runs-on: ubuntu-latest
      timeout-minutes: 30
      needs: build-apk
      if: inputs.GITHUB_UPLOAD

      steps:
        - name: Download Already Built APKs
          uses: actions/download-artifact@main
          with:
            name: Built-APKs
        - name: Get Date
          id: get-date
          run: |
            echo "date=$(TZ='Asia/Seoul' date +"%Y/%m/%d_%H.%M.%S")" >> $GITHUB_OUTPUT
            curl https://github.com/nikhilbadyal/docker-py-revanced/blob/changelogs/changelog.md > changelog.md

      #- name: Delete Older Releases
        #uses: nikhilbadyal/ghaction-rm-releases@v0.0.5
        #with:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #RELEASE_PATTERN: "Build*"

        - name: Upload Build Artifact
          uses: ncipollo/release-action@main
          with:
            artifacts: "*-output.apk"
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: Build_${{ steps.get-date.outputs.date }}
            artifactErrorsFailBuild: true

        - name: Sleep for 10 seconds
          run: |
            sleep 10
